### ISSUE TITLE
重複について

### ISSUE THREAD

**Issue by ookinahatake** [atmarksharp/svl12000-everyday#1]
SVL12000の単語リストを探していてたどり着きました。非常に助かっています。

Level5の中身を見た時に気づいたのですが、Level4の内容と全く一緒の物になっているようです。
また、Level8もLevel7と同じになっていました。

こちら修正予定等ありますでしょうか。よろしくお願いいたいします。

**Comment by JosephSyuya** [comment]
私も困ってます。

**Comment by atmarksharp** [comment]
ご報告いただきありがとうございます。
ご報告ありがとうございます。確かに同じものになっているようですね。単純ミスでした。

```bash
$ diff levels.level4.csv levels.level5.csv
$ diff levels.level7.csv levels.level8.csv
```

元々このCSVは、http://toeic-town.net/alc-svl12000-free-download/ で紹介されている英単語クラブさんのPDFから抜き出して作ったものです。

英単語クラブ http://eitango.tkm7.com/ は現在は閉鎖されており、この紹介元のtoeic-town.netで新たなPDFが配布されているようですので、そちらから作り直します。しばらくお待ちください。

**Comment by atmarksharp** [comment]
対応しました。

ただこれらのファイルの著作権は元々、英単語クラブやTOEIC TOWN、そしてアルクに帰属しているので、使用法には十分注意されてください。
